version: '3'

services:
  tfboard:
    build:
      context: tfboard
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.7"
        TF_VERSION: "2.0.0"

    ports:
      - "6006:6006"

    environment:
      - LOGS_PATH=/var/models/

    volumes:
    # TODO: here could be better way to mount all softlinks
    - /var/models/1:/var/models/1
    - /var/models/2:/var/models/2

    restart: always
